

name = "免费节点分享"

description = "🚀 免费订阅地址，🚀 免费节点，🚀 每天更新，共享节点，节点质量高可用，完全免费。免费v2ray节点每日更新。免费clash订阅地址，免费翻墙、免费科学上网、免费梯子、免费ss/v2ray/trojan节点、翻墙梯子。"
homepage = "https://github.com/freenodess/freenode"
demosite = "https://freenodess.github.io/freenode/zh/"
tags = [
  "responsive",
  "blog",
  "clean",
  "minimal",
  "light",
  "dark",
  "fast",
  "multilingual",
  "search",
  "seo",
  "chroma",
  "personal"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "twitter-cards",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search",
  "breadcrumbs",
  "reading-time",
  "word-count",
  "code-copy",
  "comments",
  "edit-post",
  "canonical-link",
  "profile-mode",
  "home-info-mode",
  "related-posts",
  "rss",
  "multiple-authors",
  "post-nav-links"
]
min_version = "0.146.0"

[author]
  name = "Aditya Telange"
  homepage = "https://github.com/adityatelange"

# If porting an existing theme
[original]
  name = "Paper"
  author = "nanxiaobei"
  homepage = "https://github.com/nanxiaobei"
  repo = "https://github.com/nanxiaobei/hugo-paper/"
