name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main # 如果你的默认分支是 master，请改成 master
  workflow_dispatch:

permissions:
    contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # 必须递归拉取主题子模块
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true # PaperMod 需要 Hugo Extended 版本

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          commit_message: "Auto-deploy by GitHub Actions"
          keep_files: false
